"""
Constantes usadas no processo de análise de mensagens.
"""

from typing import Dict, List, Set

# Palavras-chave que indicam a necessidade de integrações ou ferramentas.
# Usar um Set (conjunto) torna a busca por palavras muito mais rápida.
PALAVRAS_CHAVE_DE_SISTEMA: Set[str] = {
    # ===== VERBOS DE AÇÃO (CORE) =====
    "enviar",
    "send",
    "mandar",
    "encaminhar",
    "disparar",
    "criar",
    "create",
    "gerar",
    "fazer",
    "produzir",
    "agendar",
    "schedule",
    "marcar",
    "reservar",
    "abrir",
    "open",
    "acessar",
    "visualizar",
    "ver",
    "compartilhar",
    "share",
    "dividir",
    "colaborar",
    "sincronizar",
    "sync",
    "atualizar",
    "update",
    "deletar",
    "delete",
    "remover",
    "apagar",
    "excluir",
    "editar",
    "edit",
    "modificar",
    "alterar",
    "corrigir",
    "salvar",
    "save",
    "gravar",
    "arquivar",
    "buscar",
    "search",
    "procurar",
    "encontrar",
    "localizar",
    "listar",
    "mostrar",
    "exibir",
    "baixar",
    "download",
    "fazer download",
    "subir",
    "upload",
    "fazer upload",
    "enviar arquivo",
    # ===== EMAIL & COMUNICAÇÃO =====
    "email",
    "e-mail",
    "gmail",
    "mensagem",
    "message",
    "responder",
    "reply",
    "reencaminhar",
    "forward",
    "destinatario",
    "recipient",
    "assunto",
    "subject",
    "rascunho",
    "draft",
    "caixa de entrada",
    "inbox",
    "spam",
    "lixeira",
    "trash",
    "enviados",
    "sent",
    # ===== DOCUMENTOS & ARQUIVOS =====
    "documento",
    "document",
    "doc",
    "docx",
    "planilha",
    "spreadsheet",
    "sheet",
    "excel",
    "xlsx",
    "apresentacao",
    "presentation",
    "ppt",
    "pptx",
    "tabela",
    "table",
    "dados",
    "arquivo",
    "file",
    "pasta",
    "folder",
    "pdf",
    "word",
    "powerpoint",
    "formulario",
    "form",
    # ===== GOOGLE WORKSPACE =====
    "drive",
    "google drive",
    "gdrive",
    "docs",
    "google docs",
    "sheets",
    "google sheets",
    "google slides",
    "google forms",
    "meet",
    "google meet",
    "hangout",
    "armazenamento",
    "storage",
    "nuvem",
    "cloud",
    # ===== CALENDÁRIO & AGENDA =====
    "calendario",
    "calendar",
    "agenda",
    "evento",
    "event",
    "compromisso",
    "appointment",
    "reuniao",
    "meeting",
    "encontro",
    "call",
    "videochamada",
    "video call",
    "conferencia",
    "horario",
    "data",
    "date",
    "lembrete",
    "reminder",
    "notificacao",
    "notification",
    "disponibilidade",
    "availability",
    "livre",
    "ocupado",
    "convidar",
    "invite",
    "participante",
    "attendee",
    # ===== CONTATOS & PESSOAS =====
    "contato",
    "contact",
    "contatos",
    "contacts",
    "pessoa",
    "people",
    "usuario",
    "user",
    "grupo",
    "group",
    "equipe",
    "team",
    "convidado",
    "guest",
    "participant",
    # ===== TAREFAS & PRODUTIVIDADE =====
    "tarefa",
    "task",
    "todo",
    "to-do",
    "nota",
    "note",
    "notes",
    "anotacao",
    "checklist",
    "lista",
    "projeto",
    "project",
    "prazo",
    "deadline",
    "vencimento",
    "due date",
    # ===== INTEGRAÇÃO & API =====
    "integracao",
    "integration",
    "api",
    "webhook",
    "oauth",
    "autenticacao",
    "authentication",
    "token",
    "permissao",
    "permission",
    "acesso",
    "access",
    "conectar",
    "connect",
    "vincular",
    "link",
    # ===== FINANCEIRO (BRASIL) =====
    "boleto",
    "pix",
    "transferencia",
    "transfer",
    "fatura",
    "invoice",
    "nota fiscal",
    "nf",
    "cobranca",
    "charge",
    "pagamento",
    "payment",
    "recibo",
    "receipt",
    "comprovante",
    "proof",
    "valor",
    "amount",
    "preco",
    "price",
    # ===== ESPECÍFICOS DO GOOGLE =====
    "google",
    "workspace",
    "gsuite",
    "g suite",
    "gcal",
    "gdocs",
    "gsheets",
    "slides",
    "forms",
}

# Cache de scopes para padrões conhecidos (evita reprocessamento)
SCOPE_CACHE: Dict[str, List[str]] = {
    # ===== CALENDÁRIO (1 scope) =====
    "agendar reuniao": ["https://www.googleapis.com/auth/calendar"],
    "marcar reuniao": ["https://www.googleapis.com/auth/calendar"],
    "criar evento": ["https://www.googleapis.com/auth/calendar"],
    "marcar compromisso": ["https://www.googleapis.com/auth/calendar"],
    "agendar compromisso": ["https://www.googleapis.com/auth/calendar"],
    "criar lembrete": ["https://www.googleapis.com/auth/calendar"],
    "verificar agenda": ["https://www.googleapis.com/auth/calendar.readonly"],
    "consultar calendario": ["https://www.googleapis.com/auth/calendar.readonly"],
    # ===== GMAIL (1 scope) =====
    "enviar email": ["https://mail.google.com/"],
    "mandar email": ["https://mail.google.com/"],
    "encaminhar email": ["https://mail.google.com/"],
    "responder email": ["https://mail.google.com/"],
    "criar rascunho": ["https://mail.google.com/"],
    "ler email": ["https://mail.google.com/"],
    "buscar email": ["https://mail.google.com/"],
    # ===== SHEETS (2 scopes - SEMPRE!) =====
    "criar planilha": [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive",
    ],
    "abrir planilha": [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive",
    ],
    "editar planilha": [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive",
    ],
    # ===== DOCS (2 scopes - SEMPRE!) =====
    "criar documento": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/documents",
    ],
    "abrir documento": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/documents",
    ],
    "editar documento": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/documents",
    ],
    # ===== DRIVE GENÉRICO (1 scope) =====
    "compartilhar arquivo": ["https://www.googleapis.com/auth/drive"],
    "fazer upload": ["https://www.googleapis.com/auth/drive.file"],
    "baixar arquivo": ["https://www.googleapis.com/auth/drive.readonly"],
    "listar arquivos": ["https://www.googleapis.com/auth/drive.readonly"],
    # ===== FINANCEIRO (scope customizado) =====
    "gerar boleto": ["boleto"],
    "emitir boleto": ["boleto"],
    "criar pix": ["pix"],
    "gerar pix": ["pix"],
}
